{
    "config": {
        "abort": {
            "already_configured": "Ger\u00e4t ist bereits konfiguriert",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich",
            "unknown": "Unerwarteter Fehler"
        },
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_auth": "Ung\u00fcltige Authentifizierung",
            "unknown": "Unerwarteter Fehler"
        },
        "step": {
            "authenticate": {
                "data": {
                    "api_key": "API-Schl\u00fcssel"
                }
            },
            "user": {
                "data": {
                    "api_key": "API-Schl\u00fcssel",
                    "host": "Host",
                    "port": "Port"
                }
            }
        }
    }
}